services:
  web:
    build: .
    container_name: web
    command: bash -c "python ./manage.py collectstatic --noinput && python ./manage.py migrate && gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 0 --reload project.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - GCP_LOCATION=us-east4
      - GCP_PROJECT=my-project
      - GOOGLE_APPLICATION_CREDENTIALS=application_default_credentials.json
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "1g"

  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d database" ]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: on-failure

  tasks-emulator:
    container_name: tasks-emulator
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: -host 0.0.0.0 -port 8123
    ports:
      - "8123:8123"

volumes:
  postgres_data:
