# Generated by Django 5.1.2 on 2024-10-25 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
